### PR TITLE
Parse mergetags

### PR DESCRIPTION
**Pull request by magik6k**
When a signed tag is merged, a mergetag object is embedded into the merge commit so that one can verify the signature.

### CODE REVIEW

**Review by vmx — COMMENTED** [review]
The code looks good. Can you please add to the test data commit the information on how to generate the test data? This way someone can update the data if that's needed.

**Comment by magik6k** [comment]
done

**Review by vmx — APPROVED** [review]
Putting the information into the README is even better.

**Comment by vmx** [comment]
Sorry for not spotting this earlier. The commitlint on Jenkins failes. The problem is that the text after the colon needs to start with a lower case later.

You can easily change the commit messages with running `git rebase -i HEAD~3` and then putting a `r` in front of the commits.

If that's too much hassle, let me know, I'd be OK merging it nonetheless as this is really a small thing.

**Comment by magik6k** [comment]
Should be fixed now. No idea why it fails on mac though.

**Review by vmx — APPROVED** [review]

**Comment by vmx** [comment]
CI actually passed, the failing part is outdated CI stuff.

**Pull request merged**
